#profile:
  server:
    port: 8763
  spring:
    application:
      name: questionnire
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: dev123456
      driver-class-name: org.postgresql.Driver
      validationQuery: SELECT 'X'
      testWhileIdle: true
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: sunxikai928.com.github.springcloud.model # 注意：对应实体类的路径