#server:
#  port: ${profile.server.port}

spring:
  profiles:
    active: dev
  application:
    name: questionnire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: ${profile.spring.datasource.url}
#    username: ${profile.spring.datasource.username}
#    password: ${profile.spring.datasource.password}
#    driver-class-name: ${profile.spring.datasource.driver-class-name}
#    validationQuery: ${profile.spring.datasource.validationQuery}
#    testWhileIdle: ${profile.spring.datasource.testWhileIdle}
#    max-idle: ${profile.spring.datasource.max-idle}
#    max-wait: ${profile.spring.datasource.max-wait}
#    min-idle: ${profile.spring.datasource.min-idle}
#    initial-size: ${profile.spring.datasource.initial-size}

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${profile.eureka.client.serviceUrl.defaultZone}

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: sunxikai928.com.github.springcloud.model # 注意：对应实体类的路径