profile:
  server:
    port: 8764
  spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: dev123456
      driver-class-name: org.postgresql.Driver
      validationQuery: SELECT 'X'
      testWhileIdle: true
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
