server:
  port: 8762

spring:
  application:
    name: questionnire
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@//120.52.79.47:80/orcl
    username: visitdatadev
    password: dev123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: sunxikai928.com.github.springcloud.model # 注意：对应实体类的路径