# 服务器配置
server:
  port: ${profile.server.port}

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: gateway

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${profile.eureka.client.serviceUrl.defaultZone}

# 网关配置
zuul:
  routes:
    api-a:
      path: /questionnire/**
      serviceId: questionnire